# Generated by Django 4.2.10 on 2024-02-28 16:29

import blog.utils
from django.db import migrations, models
import django_ckeditor_5.fields
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=127, unique=True)),
                ('thumbnail', models.ImageField(default='default/default.png', upload_to=utils.utils.category_path)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('format', models.CharField(choices=[('JPEG', 'jpeg'), ('JPG', 'jpg'), ('PNG', 'png'), ('GIF', 'gif'), ('BMP', 'bmp'), ('SVG', 'svg'), ('WebP', 'webp'), ('TIFF', 'tiff'), ('MP4', 'mp4'), ('AVI', 'avi'), ('MKV', 'mkv'), ('MOV', 'mov'), ('WMV', 'wmv'), ('FLV', 'flv'), ('WebM', 'webm'), ('MP3', 'mp3'), ('WAV', 'wav'), ('AAC', 'aac'), ('FLAC', 'flac'), ('OGG', 'ogg'), ('M4A', 'm4a'), ('AIFF', 'aiff')], editable=False, max_length=5)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], editable=False, max_length=5)),
                ('file', models.FileField(upload_to=blog.utils.gallery_path)),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('preview_body', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus laborum autem, dolores inventore, beatae nam.', max_length=127)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('thumbnail', models.ImageField(default='default/default.png', upload_to=blog.utils.post_path)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
